import profile_icon from './profile_icon.png'
import type { Property } from '../types/propertyTypes'

export const assets = {
    profile_icon
}

/*
 * STATIC PROPERTY DATA
 * Replace fetchProperties() in AppContext with an API call when the backend is ready.
 * All filter fields (bedrooms, bathrooms, furnishing, postedBy, amenities, etc.) are
 * included so the sidebar filters work against real-shaped data from day one.
 */

export const dummyProperties: Property[] = [
  // ─── BUY ────────────────────────────────────────────────────────────────────
  {
    _id: 'prop001',
    title: 'Leverage Green Woods Unity C – 2 BHK',
    category: 'Buy',
    price: '₹52.42 Lac',
    priceValue: 52.42,
    area: '1165',
    areaValue: 1165,
    type: 'Residential Apartment',
    status: 'Available',
    bedrooms: 2,
    bathrooms: 2,
    furnishing: 'Furnished',
    postedBy: 'Owner',
    availableFor: ['Family', 'Single Men'],
    amenities: ['Parking', 'Lift', 'Power Backup', 'Swimming Pool', 'Gymnasium', 'Security Personnel'],
    images: [
      'https://images.unsplash.com/photo-1560185007-cde436f6a4d0',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c',
      'https://images.unsplash.com/photo-1572120360610-d971b9d7767c',
    ],
    location: 'Manish Nagar, Nagpur',
    city: 'Nagpur',
    description: 'A beautifully furnished 2 BHK flat in the heart of Nagpur. Modern interiors, excellent connectivity to major highways and IT parks.',
    availability: 'Ready to Move',
  },
  {
    _id: 'prop002',
    title: 'Prestige Skyline Heights – 3 BHK Apartment',
    category: 'Buy',
    price: '₹85 Lac',
    priceValue: 85,
    area: '1540',
    areaValue: 1540,
    type: 'Residential Apartment',
    status: 'Available',
    bedrooms: 3,
    bathrooms: 2,
    furnishing: 'Semifurnished',
    postedBy: 'Builder',
    availableFor: ['Family'],
    amenities: ['Parking', 'Lift', 'Power Backup', 'Club House', 'Park', 'Vaastu Compliant', 'Security Personnel', 'Gas Pipeline'],
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750',
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64',
      'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d',
    ],
    location: 'Dharampeth, Nagpur',
    city: 'Nagpur',
    description: 'Spacious 3 BHK apartment in a premium gated society. Vastu-compliant design with lush green surroundings and top-class amenities.',
    availability: 'Ready to Move',
  },
  {
    _id: 'prop003',
    title: 'Greenfield Villas – 4 BHK Independent Bungalow',
    category: 'Buy',
    price: '₹1.5 Cr',
    priceValue: 150,
    area: '2800',
    areaValue: 2800,
    type: 'Independent House/Villa',
    status: 'Available',
    bedrooms: 4,
    bathrooms: 4,
    furnishing: 'Semifurnished',
    postedBy: 'Dealer',
    availableFor: ['Family'],
    amenities: ['Parking', 'Power Backup', 'Park', 'Security Personnel', 'Vaastu Compliant', 'Pet Friendly', 'Swimming Pool'],
    images: [
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914',
      'https://images.unsplash.com/photo-1568605114967-8130f3a36994',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9',
    ],
    location: 'Wardha Road, Nagpur',
    city: 'Nagpur',
    description: 'Luxurious 4 BHK independent bungalow spread across 2800 sq ft. Private garden, two-car garage and 24/7 security.',
    availability: 'Within 6 Months',
  },
  {
    _id: 'prop004',
    title: 'Sai Krupa Residency – 1 BHK Starter Home',
    category: 'Buy',
    price: '₹25 Lac',
    priceValue: 25,
    area: '620',
    areaValue: 620,
    type: 'Residential Apartment',
    status: 'Available',
    bedrooms: 1,
    bathrooms: 1,
    furnishing: 'Unfurnished',
    postedBy: 'Owner',
    availableFor: ['Family', 'Single Men', 'Single Women'],
    amenities: ['Parking', 'Power Backup'],
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688',
      'https://images.unsplash.com/photo-1536376072261-38c75010e6c9',
      'https://images.unsplash.com/photo-1554995207-c18c203602cb',
    ],
    location: 'Hingna Road, Nagpur',
    city: 'Nagpur',
    description: 'Affordable 1 BHK flat, ideal for first-time buyers or investors. Ready-to-move condition with clear titles.',
    availability: 'Ready to Move',
  },
  {
    _id: 'prop005',
    title: 'Royal Palm Estate – 5 BHK Luxury Villa',
    category: 'Buy',
    price: '₹3 Cr',
    priceValue: 300,
    area: '4500',
    areaValue: 4500,
    type: 'Independent House/Villa',
    status: 'Available',
    bedrooms: 5,
    bathrooms: 5,
    furnishing: 'Furnished',
    postedBy: 'Builder',
    availableFor: ['Family'],
    amenities: ['Parking', 'Lift', 'Power Backup', 'Swimming Pool', 'Gymnasium', 'Club House', 'Park', 'Security Personnel', 'Gas Pipeline', 'Vaastu Compliant', 'Pet Friendly'],
    images: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811',
      'https://images.unsplash.com/photo-1599427303058-f04cbcf4756f',
      'https://images.unsplash.com/photo-1617806118233-18e1de247200',
    ],
    location: 'Katol Road, Nagpur',
    city: 'Nagpur',
    description: 'Ultra-premium 5 BHK villa with private pool, home theatre and smart-home automation. Gated township with 24×7 security.',
    availability: 'Within 1 Year',
  },
  {
    _id: 'prop016',
    title: 'Studio Nest – 1 RK Modern Studio',
    category: 'Buy',
    price: '₹18 Lac',
    priceValue: 18,
    area: '380',
    areaValue: 380,
    type: '1 RK/ Studio Apartment',
    status: 'Available',
    bedrooms: 1,
    bathrooms: 1,
    furnishing: 'Furnished',
    postedBy: 'Owner',
    availableFor: ['Single Men', 'Single Women'],
    amenities: ['Parking', 'Wifi', 'Security Personnel', 'Power Backup'],
    images: [
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb',
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858',
    ],
    location: 'Sitabuldi, Nagpur',
    city: 'Nagpur',
    description: 'Compact and fully furnished studio apartment in the city centre. Perfect for working professionals, central to all facilities.',
    availability: 'Ready to Move',
  },

  // ─── RENT ───────────────────────────────────────────────────────────────────
  {
    _id: 'prop006',
    title: 'Comfort Heights – 2 BHK for Rent',
    category: 'Rent',
    price: '₹15,000/mo',
    priceValue: 15,
    area: '1050',
    areaValue: 1050,
    type: 'Residential Apartment',
    status: 'Available',
    bedrooms: 2,
    bathrooms: 2,
    furnishing: 'Semifurnished',
    postedBy: 'Owner',
    availableFor: ['Family', 'Single Women'],
    amenities: ['Parking', 'Lift', 'Power Backup', 'Security Personnel'],
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c349d24',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2',
    ],
    location: 'Ramdaspeth, Nagpur',
    city: 'Nagpur',
    description: 'Well-maintained 2 BHK semi-furnished flat available for rent. Ideal for families and working couples. Easy access to main market.',
    availability: 'Ready to Move',
  },
  {
    _id: 'prop007',
    title: 'Urban Nest – 1 BHK Furnished Flat',
    category: 'Rent',
    price: '₹8,000/mo',
    priceValue: 8,
    area: '550',
    areaValue: 550,
    type: 'Residential Apartment',
    status: 'Available',
    bedrooms: 1,
    bathrooms: 1,
    furnishing: 'Furnished',
    postedBy: 'Owner',
    availableFor: ['Single Men', 'Single Women'],
    amenities: ['Wifi', 'AC Room', 'Food Service', 'Laundry Available', 'Security Personnel'],
    images: [
      'https://images.unsplash.com/photo-1536376072261-38c75010e6c9',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858',
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267',
    ],
    location: 'Sadar, Nagpur',
    city: 'Nagpur',
    description: 'Cozy fully furnished 1 BHK apartment with Wi-Fi and AC. Preferred for single professionals. All utilities included.',
    availability: 'Ready to Move',
  },
  {
    _id: 'prop008',
    title: 'Lakeview Residency – 3 BHK Premium Rent',
    category: 'Rent',
    price: '₹28,000/mo',
    priceValue: 28,
    area: '1650',
    areaValue: 1650,
    type: 'Independent House/Villa',
    status: 'Rented',
    bedrooms: 3,
    bathrooms: 3,
    furnishing: 'Furnished',
    postedBy: 'Builder',
    availableFor: ['Family', 'Tenants with Company Lease'],
    amenities: ['Parking', 'Lift', 'Power Backup', 'Club House', 'Swimming Pool', 'Gymnasium', 'Security Personnel'],
    images: [
      'https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3',
      'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde',
    ],
    location: 'Ambazari Lake Road, Nagpur',
    city: 'Nagpur',
    description: 'Premium 3 BHK fully furnished house with lake views. Equipped with high-end appliances, modular kitchen and reserved parking.',
    availability: 'Ready to Move',
  },

  // ─── COMMERCIAL ─────────────────────────────────────────────────────────────
  {
    _id: 'prop009',
    title: 'Business Hub – Ready Office Space',
    category: 'Commercial',
    price: '₹80 Lac',
    priceValue: 80,
    area: '1800',
    areaValue: 1800,
    type: 'Commercial',
    status: 'Available',
    bedrooms: 0,
    bathrooms: 2,
    furnishing: 'Unfurnished',
    postedBy: 'Builder',
    availableFor: ['Tenants with Company Lease'],
    amenities: ['Parking', 'Lift', 'Power Backup', 'Security Personnel', 'Wifi'],
    images: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c',
      'https://images.unsplash.com/photo-1497366754035-f200968a6e72',
      'https://images.unsplash.com/photo-1497366412874-3415097a27e7',
    ],
    location: 'Empress City Mall Road, Nagpur',
    city: 'Nagpur',
    description: 'Prime commercial office space in the CBD. Ready to move in. Excellent floor plate design with large windows and basement parking.',
    availability: 'Ready to Move',
  },
  {
    _id: 'prop010',
    title: 'Main Road Showroom – High Footfall Location',
    category: 'Commercial',
    price: '₹1.2 Cr',
    priceValue: 120,
    area: '950',
    areaValue: 950,
    type: 'Commercial',
    status: 'Available',
    bedrooms: 0,
    bathrooms: 1,
    furnishing: 'Unfurnished',
    postedBy: 'Dealer',
    availableFor: ['Tenants with Company Lease'],
    amenities: ['Parking', 'Power Backup', 'Security Personnel'],
    images: [
      'https://images.unsplash.com/photo-1441986300917-64674bd600d8',
      'https://images.unsplash.com/photo-1604014237800-1c9102c219da',
      'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d',
    ],
    location: 'Itwari, Nagpur',
    city: 'Nagpur',
    description: 'Strategically located showroom on main road with 35-ft frontage. High footfall area. Suitable for retail, showroom or bank branch.',
    availability: 'Ready to Move',
  },

  // ─── PLOTS / LAND ────────────────────────────────────────────────────────────
  {
    _id: 'prop011',
    title: 'Jamtha Residential Plot – RERA Approved',
    category: 'Plots/Land',
    price: '₹26.57 Lac',
    priceValue: 26.57,
    area: '1131',
    areaValue: 1131,
    type: 'Residential Land',
    status: 'Available',
    bedrooms: 0,
    bathrooms: 0,
    furnishing: 'Unfurnished',
    postedBy: 'Owner',
    availableFor: ['Family'],
    amenities: ['Park', 'Vaastu Compliant'],
    images: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef',
      'https://images.unsplash.com/photo-1464082354059-27db6ce50048',
      'https://images.unsplash.com/photo-1574362848149-11496d93a7c7',
    ],
    location: 'Jamtha, Nagpur',
    city: 'Nagpur',
    description: 'RERA-approved residential plotted development near Jamtha. Corner plot with good road access. Ideal for bungalow construction.',
    availability: 'Ready to Move',
  },
  {
    _id: 'prop012',
    title: 'Agricultural Land – Butibori Highway',
    category: 'Plots/Land',
    price: '₹45 Lac',
    priceValue: 45,
    area: '21780',
    areaValue: 21780,
    type: 'Agricultural Land',
    status: 'Available',
    bedrooms: 0,
    bathrooms: 0,
    furnishing: 'Unfurnished',
    postedBy: 'Owner',
    availableFor: ['Family'],
    amenities: [],
    images: [
      'https://images.unsplash.com/photo-1464082354059-27db6ce50048',
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef',
      'https://images.unsplash.com/photo-1574362848149-11496d93a7c7',
    ],
    location: 'Butibori, Nagpur',
    city: 'Nagpur',
    description: '5-acre agricultural land parcel on NH 7. Flat terrain with borewell and electricity. Suitable for farming or future industrial use.',
    availability: 'Ready to Move',
  },

  // ─── PROJECTS ────────────────────────────────────────────────────────────────
  {
    _id: 'prop013',
    title: 'Horizon Towers – 3 BHK Luxury Project',
    category: 'Projects',
    price: '₹95 Lac',
    priceValue: 95,
    area: '1720',
    areaValue: 1720,
    type: 'Residential Apartment',
    status: 'Available',
    bedrooms: 3,
    bathrooms: 3,
    furnishing: 'Semifurnished',
    postedBy: 'Builder',
    availableFor: ['Family'],
    amenities: ['Parking', 'Lift', 'Power Backup', 'Swimming Pool', 'Gymnasium', 'Club House', 'Park', 'Security Personnel', 'Gas Pipeline', 'Vaastu Compliant'],
    images: [
      'https://images.unsplash.com/photo-1486325212027-8081e485255e',
      'https://images.unsplash.com/photo-1575517111839-3a3843ee7f5d',
      'https://images.unsplash.com/photo-1600607687644-c7171b42498b',
    ],
    location: 'Besa, Nagpur',
    city: 'Nagpur',
    description: 'Ongoing premium township by a reputed builder. Delivery expected in Q3 2026. Earthquake-resistant RCC framed structure with 50+ amenities.',
    availability: 'Within 1 Year',
  },

  // ─── NEW LAUNCH ──────────────────────────────────────────────────────────────
  {
    _id: 'prop014',
    title: 'Pearl Greens – 2 BHK New Launch',
    category: 'New Launch',
    price: '₹48 Lac',
    priceValue: 48,
    area: '1020',
    areaValue: 1020,
    type: 'Residential Apartment',
    status: 'Available',
    bedrooms: 2,
    bathrooms: 2,
    furnishing: 'Unfurnished',
    postedBy: 'Builder',
    availableFor: ['Family', 'Single Men', 'Single Women'],
    amenities: ['Parking', 'Lift', 'Power Backup', 'Park', 'Security Personnel', 'Vaastu Compliant'],
    images: [
      'https://images.unsplash.com/photo-1585771724684-38269d6639fd',
      'https://images.unsplash.com/photo-1486325212027-8081e485255e',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750',
    ],
    location: 'Wathoda, Nagpur',
    city: 'Nagpur',
    description: 'Just launched! Early-bird pricing available. 2 BHK smart apartments with modular kitchen fittings and RERA registration. Possession: Dec 2026.',
    availability: 'More Than 1 Year',
  },
  {
    _id: 'prop015',
    title: 'Skyline Penthouse – 3 BHK New Launch',
    category: 'New Launch',
    price: '₹1.35 Cr',
    priceValue: 135,
    area: '2300',
    areaValue: 2300,
    type: 'Residential Apartment',
    status: 'Available',
    bedrooms: 3,
    bathrooms: 3,
    furnishing: 'Furnished',
    postedBy: 'Builder',
    availableFor: ['Family'],
    amenities: ['Parking', 'Lift', 'Power Backup', 'Swimming Pool', 'Gymnasium', 'Club House', 'Security Personnel', 'Gas Pipeline', 'Wifi'],
    images: [
      'https://images.unsplash.com/photo-1600566752229-250ed79470f8',
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c',
    ],
    location: 'Civil Lines, Nagpur',
    city: 'Nagpur',
    description: 'Exclusive top-floor penthouse with city skyline views. Pre-launch offer valid for first 10 registrations. Smart home enabled.',
    availability: 'Within 1 Year',
  },
];
